[project]
name = "open-amort"
version = "0.1.0"
description = "Open amortization tools"
readme = "README.md"
authors = [
    { name = "Hector Palomeque", email = "hrpalomeque@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "marimo>=0.21.1",
    "pytest>=9.0.2",
]
